### ISSUE TITLE
Incorrect "no network connection" errors when loading comments on pre-iOS 18

### ISSUE THREAD

**Issue by nativeit** [SUWULLC/Octal#311]
I’ve been a paid Octal user for a few years now, without issue, but I think the recent updates that coincide with iOS 18 may have killed the app for my old (but still perfectly functional, otherwise) iPad Pro (A1652). 

I understand support may be limited for older devices, but since this is where I primarily consume such material, I am sincerely hoping there is a chance for it to be fixed.

As of right now, the main feed loads, links to articles work, but comments never load, and neither do search results when searching for articles. 

I thought this was an open source app? I have an Apple Developer account, and I would be happy to dig into this issue, and search for a fix myself. It seems this may not be the case, I only see docs and issues in this repo, anyway. Not a big deal, but I don't like to ask for things like this without offering my own support. If there’s a way I could sponsor the fix, I would certainly consider that. 

Either way, **thanks for your efforts**, I love the app, here’s hoping I can keep using it for a few more years!

**Comment by rc1** [comment]
Same issue for me on an iPhone 14 Pro with the latest update. Comments show network error. Restarting the app and trying immediately again means they load. Later, they won’t load again.

**Comment by dangwu** [comment]
Thanks for the reports. I’ll try to repro using an iOS 16 sim tomorrow. I
use a 14 Pro myself and haven’t had issues. What iOS version are you on?

**Comment by rc1** [comment]
17.6.1
The issue only started happening this week or last but has been consistent.
Thanks for a great app (that I spend too long in 😉)

**Comment by dangwu** [comment]
@nativeit are you getting a `No network connection error`, a blank screen, or something else?

**Comment by dangwu** [comment]
Also, do you have another iOS device to see if it experiences the same issue?

**Comment by oldgalileo** [comment]
@dangwu FWIW I’m also experiencing this on an iPhone 11 Pro on iOS 16.5.1.

It seems that the comments load fine when I first open the app. Then when the app is backgrounded and then I come back, they refuse to load until I close and re-open the app.

Also noted that I haven’t taken an iOS app update, and this has just started in the last week.

**Comment by abulte** [comment]
Same here, iPhone 14, iOS 17.6.1. Tried to delete app and then reinstall, to no avail.

**Comment by dangwu** [comment]
Very strange. I'm sorry this happened, ya'll. I haven't been able to reproduce this at all (on simulator). 

When you background the app, are you backgrounding it on the comments screen, or does it happen no matter what? I'm also curious if upgrading to iOS 18 fixes the issue, if any of you can update.

**Comment by abulte** [comment]
Screenshot attached since I managed to reproduce today after restarting the app this morning. It took a few hours (6 at most, at least 1). I was on a comment thread when the app was backgrounded, but I don't know if it happens when I'm not.

I'll try with iOS 18 when I can.

![image](https://github.com/user-attachments/assets/af4a91c0-fbc1-4793-8dea-897792b679e9)

**Comment by abulte** [comment]
It's more like: I open the app, read the comments, leave the app (background). Then I come back, leave the article I was on, go back to the articles list (which seems to work fine) and click on another previously unseen one to see the comments. Then the comments won't load.

**Comment by dangwu** [comment]
Hi everyone - I may have resolved the issue (via setting specific HN Firebase URL config for the connection test). I have a new app version in TestFlight if anyone is able to test for me! https://testflight.apple.com/join/jdB8zvZG

(cc: @abulte @nativeit @oldgalileo @rc1)

**Comment by abulte** [comment]
Nice @dangwu! I just upgraded to iOS 18. I'll see in a few hours if I can reproduce, and if I can I'll try your beta.

**Comment by dangwu** [comment]
Awesome, thank you @leejoramo! I'll release a new app update ASAP.

**Comment by dangwu** [comment]
The new version has been released to the App Store. Thanks again everyone! Let me know if it still persists.

**Comment by gundy** [comment]
I'm up to date with the latest version, but still seeing these issues :(.  Let me know if there's anything I can do to help determine what's going on. 

IPhone 14 Pro, iOS 17.6.1

**Comment by rc1** [comment]
Same. I reverted back to the testflight install. Can’t say for sure I haven’t see it happen on that. Will report back if I do.

**Comment by Starkrights** [comment]
Regrettably, it seems I'm still dealing with this issue after the update. Attached is a short screen recording of the issue, that also shows the AppStore noting the latest version being installed, and opening YouTube as a sanity check that my internet is indeed working.

It appears that I can load the links in the in-app safari, but comments refuse to load. I probably had the app backgrounded for ~5-10 minutes? Even the article I previously had open (*BSDs article opened towards the end of the screen cap) appears to have lost the comments & refuses to get them back :/.

**Comment by dangwu** [comment]
Darn, I'll try to come up with another solution then. I guess the Firebase connection test API isn't reliable, so I'll come up with a different solution soon. Thanks for letting me know

**Comment by dangwu** [comment]
@rc1 the TestFlight build is the same exact build as the App Store build, so it won't help you. Are you also on iOS 17?

@Starkrights Are you also on iOS 17?

**Comment by Starkrights** [comment]
I'm actually pretty behind on this device- I'm on iOS 16.2.

@dangwu were you using the firebase connection API prior to update 4.16? That update, as limited and unrelated as the scope seems ("Updated app icon to support light, dark, and tinted appearances in iOS 18"), seems to be pretty on the dot with when this bug started to crop up.

**Comment by Starkrights** [comment]
For thoroughness/posterity, I managed to get the testflight build to repro as well. [screencap](https://imgur.com/a/VrAiuPO)

**Comment by dangwu** [comment]
Thanks, I think this is definitely a pre-iOS 18 issue that is 100% tied to the Firebase SDK update I did when adding the dark mode icons. I went from a really old version to the latest one. I've seen other reports from other Firebase users of this identical issue, so I'm confident it's Firebase. I didn't make any significant code changes otherwise. To fix the issue once and for all, I'm going to stop using the Firebase API that has the problem, since it seems unsolved.

**Comment by Starkrights** [comment]
@dangwu if the refactor is looking like it's gonna be a bit, would it be possible to push the last working version (4.15.1 it looks like?) to TestFlight? I haven't done much in the way of iOS dev, so I don't even know if that's possible, but just a thought!

For clarity of tone: I recognize the "solo-dev whose project is not their job" struggle, so please do take your time with the refactor/fix. I have no timeframe expectation, I just love using your app, and I'd imagine that sentiment is mirrored by most (if not all) in this thread :)

**Comment by dangwu** [comment]
@Starkrights No worries with tone - the fix is ready. The unfortunate issue (that keeps happening) is that Apple is blocking my app update because they want me to add a `Delete Account` option to the app. I added a button that lets the user send an email to HN to request account deletion (since that's all YC offers), but that's not enough. I'm in the appeal process at the moment. App Store reviewers are unfortunately clueless when it comes to 3rd party client apps like Octal so I'm not sure how long this is going to take.

**Comment by dangwu** [comment]
@Starkrights Out of curiosity, is there any reason you can't use iOS 18? Or are you on iOS 18?

**Comment by Starkrights** [comment]
Ah, classic. Best of luck with that headache.

As to why I'm not on iOS 18 (currently on 16.2), to be honest I really just try and keep this device downgraded in case a jailbreak comes along for this model/version (thusfar an unfruitful endeavor haha).

**Comment by dangwu** [comment]
This should be fixed now with the 4.16.3 update today. Let me know if it persists

**Comment by Starkrights** [comment]
@nativeit @gundy @rc1 @oldgalileo are y'all seeing the issue resolved on the latest version? It seems like I'm still having trouble with it after a number of app restarts, as well as a couple phone reboots :/

**Comment by dangwu** [comment]
@Starkrights Damn, that's unfortunate. I really don't know what it could be at this point. The app is directly hitting the official Firebase API with no restrictions (ex. network checks). Are you seeing the no network error appear after 30 seconds of attempting to load the comments?

**Comment by gundy** [comment]
Yep, I'm still seeing it too, albeit with slightly different behaviour now. Previously the timeout would happen quite quickly, within a second or so. Now it seems to take quite a bit longer. And I might be imagining things, but it does seem to take a like longer for the issue to surface now.
